keycloak:
    auth-server-url: http://host.docker.internal:18080/auth
    realm: demo
    resource: login-app
    bearer-only: false
    public-client: true
    ssl-required: external    
    principal-attribute: preferred_username    