keycloak:
    auth-server-url: http://host.docker.internal:18080/auth
    realm: demo
    resource: login-app-confidential
    bearer-only: true
    public-client: false
    ssl-required: external
    credentials:
        secret: "your secret"
    principal-attribute: preferred_username    